update netdat service template

diff --git a/system/netdata-init-d.in b/system/netdata-init-d.in
--- a/system/netdata-init-d.in
+++ b/system/netdata-init-d.in
@@ -28,6 +28,7 @@ service_start()
 	[ -x $DAEMON_PATH ] || exit 5
 	[ ! -d $PIDFILE_PATH ] && mkdir -p $PIDFILE_PATH
 	echo -n "Starting $DAEMON..."
+	ip link add netdata type dummy || echo "inf already present"; ip addr add 169.254.254.254/32 dev netdata || echo "ip addr already present"
 	daemon $DAEMON_PATH/$DAEMON $DAEMONOPTS
 	RETVAL=$?
 	echo
@@ -42,6 +43,7 @@ service_stop()
 	RETVAL=$?
 	echo
 	[ $RETVAL -eq 0 ] && rm -f ${PIDFILE} ${LOCKFILE}
+	ip addr del 169.254.254.254/32 dev netdata || echo "unable clean up if addr" ; ip link del netdata || echo "unable clean up vinf"
 	return $RETVAL
 }
 
diff --git a/system/netdata-lsb.in b/system/netdata-lsb.in
--- a/system/netdata-lsb.in
+++ b/system/netdata-lsb.in
@@ -44,8 +44,9 @@ service_start() {
 	if [ ! -d $PIDFILE_PATH ]; then
 		mkdir -p $PIDFILE_PATH
 	fi
-	
+
 	log_daemon_msg "Starting real-time performance monitoring" "netdata"
+	ip link add netdata type dummy || echo "inf already present"; ip addr add 169.254.254.254/32 dev netdata || echo "ip addr already present"
 	start_daemon -p $PIDFILE $DAEMON_PATH/$DAEMON $DAEMONOPTS
 	RETVAL=$?
 	log_end_msg $RETVAL
@@ -61,6 +62,7 @@ service_stop() {
 	if [ $RETVAL -eq 0 ]; then
 		rm -f ${PIDFILE}
 	fi
+	ip addr del 169.254.254.254/32 dev netdata || echo "unable clean up if addr" ; ip link del netdata || echo "unable clean up vinf"
 	return $RETVAL
 }
 
